:timeout: 25
:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 10 %>
:queues:
  - ["critical", 30] # Used for audit logging and routing. Should be emptied as soon as possible, before anything else runs.
  - ["default", 6] # Application jobs should run more often.
  - ["webhook", 3] # Used to enqueue integrations without api calls.
  - ["netout", 1] # API calls to 3rd parties not directly related to webhook processing, like webhook subscriptions and backfills.
